# Generated by Django 6.0.6 on 2026-06-12 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('idcardapio', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
                ('preco', models.DecimalField(db_column='Preco', decimal_places=2, max_digits=5)),
                ('descricao', models.TextField(db_column='Descricao')),
                ('status', models.SmallIntegerField(db_column='Status')),
                ('categoria', models.CharField(db_column='Categoria', max_length=45)),
            ],
            options={
                'db_table': 'cardapio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('celular', models.CharField(db_column='Celular', max_length=15)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('empresa', models.CharField(blank=True, db_column='Empresa', max_length=45, null=True)),
                ('senha', models.CharField(blank=True, db_column='Senha', max_length=200, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('status_pedido', models.CharField(db_column='Status_pedido', max_length=45)),
                ('preco_total', models.DecimalField(db_column='Preco_total', decimal_places=2, max_digits=10)),
                ('mesa', models.IntegerField(db_column='Mesa')),
                ('horario_pedido', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.cliente')),
            ],
            options={
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('idcomanda', models.AutoField(db_column='idComanda', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(db_column='Quantidade')),
                ('observacoes', models.CharField(blank=True, db_column='Observacoes', max_length=50, null=True)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cardapio', models.ForeignKey(db_column='Cardapio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.cardapio')),
                ('pedido_idpedido', models.ForeignKey(db_column='Pedido_idPedido', on_delete=django.db.models.deletion.DO_NOTHING, to='api.pedido')),
            ],
            options={
                'db_table': 'comanda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('idavaliacao', models.AutoField(db_column='idAvaliacao', primary_key=True, serialize=False)),
                ('nota', models.PositiveIntegerField(db_column='Nota')),
                ('comentarios', models.TextField(blank=True, db_column='Comentarios', null=True)),
                ('id_pedido', models.OneToOneField(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.pedido')),
            ],
            options={
                'db_table': 'avaliacao',
                'managed': True,
            },
        ),
    ]
