# Generated by Django 6.0.6 on 2026-06-22 01:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='pedido',
            name='horario_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
