# Generated by Django 6.0.6 on 2026-06-22 01:49

from django.db import migrations
import cloudinary.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cardapio_imagem_alter_pedido_horario_pedido'),
    ]

    operations = [

        migrations.AddField(
            model_name='cardapio',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
