# Generated by Django 6.0.6 on 2026-06-29 23:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20260621_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Logo')),
                ('favicon', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Configuração Admin',
                'verbose_name_plural': 'Configuração Admin',
            },
        ),
    ]
