# Generated by Django 6.0.6 on 2026-06-29 23:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adminconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminconfig',
            options={'managed': True, 'verbose_name': 'Configuração Admin', 'verbose_name_plural': 'Configuração Admin'},
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo'),
        ),
    ]
