# Generated by Django 6.0.6 on 2026-06-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_adminconfig_options_alter_adminconfig_favicon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminConfig',
        ),
    ]
